"""Reports and share links (docs/data-model.md): the object-storage-pointing
`reports` table plus a `share_links` table for hashed, expiring, revocable
sharing (ADR-0002's Phase 4 addendum). Also adds the `matched_indicator`/
`request_summary`/`redaction_applied` columns to `findings` — evidence
panels need what `packages/checks` already computes but Phase 3 discarded.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 17:15:33.637849
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('artefact_uri', sa.String(length=255), nullable=True),
    sa.Column('branding_profile_id', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_reports_scan_id_scans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('scan_id', 'format', name=op.f('uq_reports_scan_id'))
    )
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_share_links_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_links_token_hash'))
    )
    op.create_index(op.f('ix_share_links_report_id'), 'share_links', ['report_id'], unique=False)
    op.add_column('findings', sa.Column('matched_indicator', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('request_summary', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('redaction_applied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'redaction_applied')
    op.drop_column('findings', 'request_summary')
    op.drop_column('findings', 'matched_indicator')
    op.drop_index(op.f('ix_share_links_report_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
